"""FastAPI application factory and lifespan manager.

On startup the lifespan hook:
1. Ensures the ``/data`` directory exists.
2. Seeds the initial ``superadmin`` account and default settings if the
   ``users`` table is empty.
3. Starts the APScheduler instance.
4. Loads a scheduled job for every enabled monitor.
5. Registers daily maintenance jobs (retention cleanup, SSL scan).

On shutdown the lifespan hook stops the scheduler, closes the shared HTTP
client, and disposes the SQLAlchemy engine.

The built Vue frontend is served as static files from ``./static/``.  Any
path not matched by an API route falls back to ``index.html`` so that the
Vue Router can handle client-side navigation.
"""

import logging
import os
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from sqlalchemy import select

from app.checkers.http_checker import close_http_client
from app.config import get_settings
from app.db.models import AppSetting, Monitor, User
from app.db.session import AsyncSessionLocal, engine
from app.routers import (
    api_keys,
    audit_log,
    auth,
    check_results,
    groups,
    heartbeat,
    import_export,
    incidents,
    maintenance,
    monitors,
    notifications,
    settings,
    sse,
    stats,
    users,
)
from app.scheduler.engine import scheduler
from app.scheduler.manager import upsert_monitor_job
from app.services.auth_service import hash_password

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

app_settings = get_settings()


def _read_app_version() -> str:
    """Return the release version from the repository-level VERSION file.

    The Docker image copies ``VERSION`` into ``/app/VERSION`` while local
    development keeps it at the repository root.  Walking up from this file
    supports both layouts and keeps the OpenAPI version aligned with the
    image tag generated by the GHCR workflow.
    """
    for parent in Path(__file__).resolve().parents:
        version_file = parent / "VERSION"
        if version_file.exists():
            return version_file.read_text(encoding="utf-8").strip()
    return "0.2.2"


async def _seed_initial_data():
    """Create the first superadmin user and default settings on empty databases."""
    async with AsyncSessionLocal() as db:
        result = await db.execute(select(User).limit(1))
        if result.scalars().first() is not None:
            return  # Already seeded

        logger.info("First run detected — creating superadmin user")
        now = datetime.now(UTC)
        admin = User(
            username="admin",
            email="admin@localhost",
            password_hash=hash_password("admin"),
            role="superadmin",
            force_pw_change=True,
            created_at=now,
            updated_at=now,
        )
        db.add(admin)

        # Default settings
        defaults = {
            "data_retention_days": "90",
            "app_base_url": f"http://localhost:{app_settings.port}",
        }
        for key, value in defaults.items():
            db.add(AppSetting(key=key, value=value, updated_at=now))

        await db.commit()
        logger.info("Superadmin created: username=admin password=admin (CHANGE THIS NOW)")


async def _load_scheduler_jobs():
    """Register all enabled monitors with APScheduler after process startup."""
    async with AsyncSessionLocal() as db:
        result = await db.execute(select(Monitor).where(Monitor.is_enabled.is_(True)))
        monitors = result.scalars().all()
        for monitor in monitors:
            try:
                upsert_monitor_job(monitor)
            except Exception:  # one bad monitor must not stop startup
                logger.exception("Failed to schedule monitor %d", monitor.id)
        logger.info("Scheduled %d monitor jobs", len(monitors))


def _register_background_jobs():
    """Register once-per-day maintenance jobs that are independent of monitors."""
    from apscheduler.triggers.cron import CronTrigger

    from app.scheduler.jobs import run_daily_retention, run_daily_ssl_scan

    scheduler.add_job(
        run_daily_retention,
        trigger=CronTrigger(hour=2, minute=0),
        id="daily_retention",
        replace_existing=True,
    )
    scheduler.add_job(
        run_daily_ssl_scan,
        trigger=CronTrigger(hour=6, minute=0),
        id="daily_ssl_scan",
        replace_existing=True,
    )


@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI lifespan hook that owns process-level resources."""
    # SQLite is file-backed in production, so the containing directory must
    # exist before SQLAlchemy opens the first connection.
    os.makedirs(os.path.dirname(app_settings.database_path), exist_ok=True)

    await _seed_initial_data()
    scheduler.start()
    await _load_scheduler_jobs()
    _register_background_jobs()
    logger.info("Observer-Lite started on port %d", app_settings.port)

    yield

    scheduler.shutdown(wait=False)
    await close_http_client()
    await engine.dispose()
    logger.info("Observer-Lite stopped")


app = FastAPI(
    title="Observer-Lite",
    version=_read_app_version(),
    lifespan=lifespan,
    docs_url="/api/docs",
    redoc_url=None,
)

# API routers
app.include_router(auth.router)
app.include_router(users.router)
app.include_router(monitors.router)
app.include_router(stats.router)
app.include_router(groups.router)
app.include_router(incidents.router)
app.include_router(check_results.router)
app.include_router(notifications.router)
app.include_router(maintenance.router)
app.include_router(heartbeat.router)
app.include_router(api_keys.router)
app.include_router(settings.router)
app.include_router(audit_log.router)
app.include_router(sse.router)
app.include_router(import_export.router)


def _index_static_files(root: Path) -> dict[str, Path]:
    """Map URL paths to files that already live under *root*.

    The request path is only used as a dictionary key. It is never joined onto
    the filesystem, so a ``../`` segment cannot escape the static directory.
    """
    return {
        path.relative_to(root).as_posix(): path
        for path in root.rglob("*")
        if path.is_file()
    }


# Static files (built frontend)
_static_dir = (Path(__file__).parent.parent / "static").resolve()
_static_files = _index_static_files(_static_dir) if _static_dir.is_dir() else {}
_index_file = _static_files.get("index.html")
if _index_file is not None:
    _assets_dir = _static_dir / "assets"
    if _assets_dir.is_dir():
        app.mount("/assets", StaticFiles(directory=str(_assets_dir)), name="assets")

    @app.get("/{full_path:path}", include_in_schema=False)
    async def spa_fallback(full_path: str):
        # Unknown paths serve the SPA shell so Vue Router can handle them.
        return FileResponse(_static_files.get(full_path, _index_file))
